import fs from 'fs';

export default class Exporter {

  constructor({filename, tasks, plugins}) {
    this.filename = filename;
    this.tasks = tasks;
    this.plugins = plugins;

    this.headline = `
    /**
     * This file was automatically generated by Gulpnoir
     * To find out more, visit https://github.com/VYNYL/gulpnoir
     **/
    `;
  }
  _writePlugins() {
    let result = [];
    for (let plugin of this.plugins) {
      let pluginName = plugin[0];
      let pluginFriendlyName = pluginName.replace(/gulp-/, '').replace(/-([a-z])/g, (full, letter) => {
        return letter.toUpperCase();
      });
      result.push(`import ${pluginFriendlyName} from '${plugin[0]}';`);
    }
    result.push('');
    return result;
  }

  _writeTasks() {
    let result = [];
    for (let task of this.tasks) {
      result.push(`export function ${task[1].get('name')}() {`);
      result.push(`}`);
    }
    result.push('');
    return result;
  }

  write() {
    let fileLines = [];
    fileLines.push(this.headline);
    fileLines.push(...this._writePlugins());
    fileLines.push(...this._writeTasks());
    fs.writeFile(this.filename, fileLines.join('\n'));
  }

}
